
DOMAIN_name = "biology"

TEXTS = [
    "DNA polymerase synthesizes new DNA strands during replication.",
    "Helicase unwinds the DNA double helix at the replication fork.",
    "Leading strand synthesis proceeds continuously in the 5' to 3' direction.",
    "Lagging strand synthesis produces Okazaki fragments that are later joined.",
    "DNA ligase seals phosphodiester bonds to connect DNA fragments.",
    "RNA primase generates short RNA primers needed for DNA synthesis.",
    "DNA replication uses complementary base pairing to copy genetic information.",
    "Replication fidelity is improved by proofreading activity of DNA polymerase.",
    "Mismatch repair corrects replication errors that escape proofreading.",
    "Telomerase extends telomeres to prevent chromosome shortening in some cells.",

    "Transcription begins when RNA polymerase binds a promoter sequence on DNA.",
    "mRNA processing in eukaryotes includes 5' capping and 3' polyadenylation.",
    "Introns are removed from pre-mRNA through splicing by the spliceosome.",
    "Alternative splicing allows one gene to produce multiple protein variants.",
    "Translation uses tRNA molecules to match amino acids with mRNA codons.",
    "Ribosomes catalyze peptide bond formation during protein synthesis.",
    "Start codons initiate translation and define the reading frame.",
    "Stop codons terminate translation and release the polypeptide chain.",
    "Mutations can alter protein function by changing amino acid sequences.",
    "Gene expression can be regulated at transcriptional and post-transcriptional levels.",

    "Cell membranes form selective barriers using phospholipid bilayers.",
    "Membrane proteins enable transport, signaling, and cell recognition functions.",
    "Diffusion moves molecules down a concentration gradient without energy input.",
    "Osmosis is the diffusion of water across a semipermeable membrane.",
    "Facilitated diffusion uses transport proteins but does not require ATP.",
    "Active transport moves molecules against a gradient using cellular energy.",
    "The sodium-potassium pump maintains membrane potential in animal cells.",
    "Endocytosis allows cells to internalize macromolecules using vesicles.",
    "Exocytosis exports materials from cells through vesicle fusion with the membrane.",
    "Membrane fluidity depends on lipid composition and cholesterol content.",

    "Mitosis distributes duplicated chromosomes into two identical daughter cells.",
    "Meiosis produces haploid gametes and increases genetic diversity.",
    "Crossing over exchanges genetic material between homologous chromosomes.",
    "Independent assortment contributes to variation in gamete combinations.",
    "Cell cycle checkpoints regulate progression and prevent uncontrolled division.",
    "Cyclins and cyclin-dependent kinases coordinate cell cycle transitions.",
    "Apoptosis is programmed cell death that prevents damaged cell survival.",
    "Cancer can result from mutations in genes controlling cell growth and division.",
    "Stem cells can differentiate into specialized cell types under regulatory cues.",
    "Cell signaling pathways coordinate development and tissue maintenance.",

    "Enzymes act as biological catalysts by lowering activation energy barriers.",
    "Enzyme active sites bind substrates through specific molecular interactions.",
    "Competitive inhibition blocks substrate binding at the enzyme active site.",
    "Noncompetitive inhibition reduces enzyme activity by changing enzyme structure.",
    "Allosteric regulation modifies enzyme function through binding at other sites.",
    "ATP hydrolysis provides energy for cellular processes and mechanical work.",
    "Cellular respiration generates ATP through glycolysis, Krebs cycle, and oxidative phosphorylation.",
    "Electron transport chains create proton gradients used by ATP synthase.",
    "Photosynthesis captures light energy to produce ATP and NADPH in chloroplasts.",
    "The Calvin cycle fixes carbon dioxide into sugars using energy from light reactions."
]