DOMAIN_name = "chemistry"

TEXTS = [
    "Atoms consist of a nucleus surrounded by electrons in quantized energy levels.",
    "The atomic number equals the number of protons in the nucleus.",
    "Isotopes differ in neutron number while keeping the same proton number.",
    "Electron configurations explain periodic trends in atomic properties.",
    "Valence electrons determine bonding behavior and chemical reactivity.",
    "Ionization energy is the energy required to remove an electron from an atom.",
    "Electronegativity measures how strongly an atom attracts bonding electrons.",
    "Atomic radius generally decreases across a period due to increasing nuclear charge.",
    "Ionic bonds form through electrostatic attraction between oppositely charged ions.",
    "Covalent bonds form when atoms share electron pairs in molecular structures.",

    "Bond polarity occurs when electrons are shared unequally between atoms.",
    "Molecular geometry can be predicted using VSEPR theory.",
    "Intermolecular forces influence boiling points and melting points of substances.",
    "Hydrogen bonding is a strong intermolecular force involving H bonded to N, O, or F.",
    "London dispersion forces arise from temporary induced dipoles in electron clouds.",
    "Dipole-dipole forces occur between polar molecules with permanent dipoles.",
    "Stronger intermolecular forces generally increase viscosity and surface tension.",
    "The ideal gas law relates pressure, volume, temperature, and moles of gas.",
    "Real gases deviate from ideal behavior at high pressure and low temperature.",
    "Gas pressure results from molecular collisions with container walls.",

    "A mole is a unit representing Avogadro’s number of particles.",
    "Molar mass converts between mass and moles for a chemical substance.",
    "Balanced chemical equations conserve mass by conserving atoms of each element.",
    "Stoichiometry relates reactant and product amounts using mole ratios.",
    "Limiting reactants determine the maximum amount of product formed in a reaction.",
    "Percent yield compares actual yield to theoretical yield in chemical synthesis.",
    "Solutions are homogeneous mixtures of solutes dissolved in solvents.",
    "Molarity measures solution concentration as moles of solute per liter of solution.",
    "Colligative properties depend on solute particle number rather than identity.",
    "Boiling point elevation occurs when solute lowers vapor pressure of a solvent.",

    "Chemical kinetics studies the rates of chemical reactions and their mechanisms.",
    "Reaction rate depends on concentration, temperature, and activation energy barriers.",
    "Catalysts increase reaction rates by lowering activation energy without being consumed.",
    "The Arrhenius equation relates temperature to reaction rate constants.",
    "Exothermic reactions release heat energy to the surroundings.",
    "Endothermic reactions absorb heat energy from the surroundings.",
    "Enthalpy change measures heat transfer at constant pressure.",
    "Entropy reflects the number of possible microstates of a system.",
    "Gibbs free energy determines spontaneity through ΔG = ΔH − TΔS.",
    "Equilibrium occurs when forward and reverse reaction rates are equal.",

    "The equilibrium constant quantifies product-to-reactant ratios at equilibrium.",
    "Le Chatelier’s principle predicts shifts in equilibrium due to stress changes.",
    "Acids donate protons while bases accept protons in Brønsted-Lowry theory.",
    "pH is the negative logarithm of hydrogen ion concentration in solution.",
    "Buffers resist pH changes through conjugate acid-base pairs.",
    "Redox reactions involve electron transfer between oxidized and reduced species.",
    "Oxidation states help track electron movement in redox processes.",
    "Electrochemical cells convert chemical energy into electrical energy.",
    "Organic chemistry focuses on carbon compounds and functional group behavior.",
    "Reaction mechanisms explain step-by-step bond breaking and formation in reactions."
]