DOMAIN_name = "computer_science"

TEXTS = [
    "Computer science studies computation, algorithms, and information systems.",
    "An algorithm is a finite, well-defined sequence of steps to solve a problem.",
    "Time complexity describes how runtime grows as input size increases.",
    "Space complexity describes how memory usage grows as input size increases.",
    "Big-O notation expresses an upper bound on growth rate of an algorithm.",
    "Data structures organize information for efficient access and modification.",
    "Arrays store elements in contiguous memory locations with index-based access.",
    "Linked lists store elements as nodes connected by pointers or references.",
    "Stacks implement last-in-first-out behavior for push and pop operations.",
    "Queues implement first-in-first-out behavior for enqueue and dequeue operations.",

    "Trees represent hierarchical structures with parent-child relationships.",
    "Binary search trees store ordered values for efficient search operations.",
    "Hash tables provide average-case constant-time lookup using hash functions.",
    "Graphs model networks using vertices and edges with weighted or unweighted links.",
    "Depth-first search explores graph paths deeply before backtracking.",
    "Breadth-first search explores graph nodes level by level using a queue.",
    "Sorting algorithms arrange data into a specified order such as ascending or descending.",
    "Binary search finds an element in a sorted array in logarithmic time.",
    "Dynamic programming optimizes problems by caching overlapping subproblem results.",
    "Recursion solves problems by reducing them to smaller instances of the same problem.",

    "Operating systems manage hardware resources and schedule program execution.",
    "Processes are independent program instances running with their own memory space.",
    "Threads allow concurrent execution within a single process.",
    "CPU scheduling determines which process runs next on the processor.",
    "Virtual memory uses disk storage to extend available RAM via paging.",
    "Memory allocation assigns and frees regions of memory for program use.",
    "File systems organize data into directories, files, and metadata structures.",
    "Computer networks enable communication between devices using protocols.",
    "The internet is a global packet-switched network using the IP protocol.",
    "IP addresses uniquely identify network interfaces for routing packets.",

    "TCP provides reliable ordered delivery using acknowledgements and retransmission.",
    "UDP provides faster best-effort delivery without reliability guarantees.",
    "Protocols define rules for message formats, timing, and error handling.",
    "Encryption transforms plaintext into ciphertext to preserve confidentiality.",
    "Symmetric encryption uses the same secret key for encryption and decryption.",
    "Asymmetric encryption uses public and private keys for secure exchange.",
    "Databases store structured data for efficient query, update, and consistency control.",
    "Relational databases use tables with rows and columns linked by keys.",
    "SQL is a declarative language for querying and managing relational databases.",
    "Indexing improves database query speed by reducing full table scans.",

    "Software engineering applies systematic practices to build maintainable systems.",
    "Version control systems track code changes and enable collaboration.",
    "Unit tests validate individual functions or modules in isolation.",
    "Integration tests validate behavior between multiple interacting components.",
    "Debugging identifies root causes of incorrect program execution.",
    "Compilers translate high-level code into machine instructions for execution.",
    "Interpreters execute code by evaluating instructions at runtime.",
    "Programming languages define syntax and semantics for expressing computations.",
    "Abstraction hides complexity by exposing only essential features of a system.",
    "Modularity organizes programs into components with clear interfaces and responsibilities."
]