DOMAIN_name = "cybersecurity"

TEXTS = [
    "Cybersecurity protects systems, networks, and data from malicious attacks.",
    "Threat actors may include criminals, insiders, or state-sponsored groups.",
    "A vulnerability is a weakness that can be exploited to compromise security.",
    "Risk can be modeled as likelihood multiplied by potential impact.",
    "Confidentiality ensures information is not disclosed to unauthorized parties.",
    "Integrity ensures data is not altered without authorization.",
    "Availability ensures systems remain usable and accessible when needed.",
    "Authentication verifies the identity of a user or device.",
    "Authorization determines what actions an authenticated identity can perform.",
    "Least privilege limits access rights to the minimum required for a task.",

    "Strong passwords reduce brute-force attacks by increasing search space.",
    "Multi-factor authentication adds additional verification beyond a password.",
    "Phishing attacks manipulate users into revealing credentials or sensitive data.",
    "Social engineering exploits human behavior rather than technical weaknesses.",
    "Malware includes viruses, worms, trojans, spyware, and ransomware.",
    "Ransomware encrypts data and demands payment for decryption keys.",
    "Firewalls filter network traffic based on configured security rules.",
    "Intrusion detection systems monitor traffic and raise alerts for anomalies.",
    "Intrusion prevention systems can actively block suspicious connections.",
    "Security logging records events for auditing and incident investigation.",

    "Encryption protects confidentiality during storage and data transmission.",
    "Symmetric encryption uses a single key for both encryption and decryption.",
    "Asymmetric encryption uses paired public and private keys.",
    "Hash functions map data to fixed-length outputs for integrity verification.",
    "Digital signatures provide integrity, authentication, and non-repudiation.",
    "Key management controls generation, storage, rotation, and revocation of keys.",
    "TLS secures web traffic by encrypting communication between client and server.",
    "Certificate authorities issue certificates that bind keys to trusted identities.",
    "Access control models include discretionary, mandatory, and role-based control.",
    "Secure configuration reduces attack surfaces by disabling unnecessary services.",

    "Patching fixes vulnerabilities discovered in software and operating systems.",
    "Vulnerability scanning identifies known weaknesses across systems.",
    "Penetration testing simulates attacker behavior to validate defenses safely.",
    "Threat modeling analyzes system assets, attack paths, and mitigation strategies.",
    "Defense in depth layers multiple controls to reduce single points of failure.",
    "Network segmentation limits attacker movement between internal systems.",
    "Backups enable recovery from ransomware, corruption, or accidental loss.",
    "Incident response defines steps for detection, containment, and recovery.",
    "Forensics analyzes evidence to understand breach scope and attacker methods.",
    "Data exfiltration is unauthorized transfer of sensitive information outward.",

    "Web security risks include SQL injection, XSS, CSRF, and command injection.",
    "Input validation prevents malicious data from triggering unexpected behavior.",
    "Zero trust assumes no implicit trust and requires continuous verification.",
    "Security monitoring detects abnormal patterns using logs and telemetry.",
    "Endpoint protection helps detect malware and suspicious behavior on devices.",
    "Supply chain attacks compromise software or dependencies before deployment.",
    "Sandboxing isolates programs to reduce damage if exploited.",
    "Privilege escalation occurs when attackers gain higher system permissions.",
    "Denial-of-service attacks disrupt availability by exhausting resources.",
    "Security governance aligns policies, controls, and audits with risk objectives."
]