DOMAIN_name = "economics"

TEXTS = [
    "Economics studies how individuals and societies allocate scarce resources.",
    "Scarcity means limited resources relative to unlimited human wants.",
    "Opportunity cost is the value of the best alternative forgone.",
    "Trade-offs occur when choosing one option requires giving up another.",
    "Incentives shape how consumers and producers make decisions.",
    "Demand is the quantity consumers are willing to buy at different prices.",
    "Supply is the quantity producers are willing to sell at different prices.",
    "Market equilibrium occurs when quantity demanded equals quantity supplied.",
    "A shortage occurs when quantity demanded exceeds quantity supplied at a price.",
    "A surplus occurs when quantity supplied exceeds quantity demanded at a price.",

    "Elasticity measures responsiveness of demand or supply to changes in price.",
    "Price elasticity of demand depends on substitutes and necessity of the good.",
    "Income elasticity measures demand changes when consumer income changes.",
    "Cross-price elasticity measures how demand changes when another price changes.",
    "Utility represents the satisfaction consumers gain from consuming goods.",
    "Consumers maximize utility subject to budget constraints.",
    "Firms maximize profit by choosing output where marginal cost equals marginal revenue.",
    "Fixed costs do not vary with output in the short run.",
    "Variable costs increase as production output increases.",
    "Marginal cost is the additional cost of producing one more unit.",

    "Perfect competition involves many firms selling identical products.",
    "Monopoly exists when a single firm controls the market supply.",
    "Oligopoly exists when a small number of firms dominate an industry.",
    "Market power is the ability of a firm to influence price above marginal cost.",
    "Externalities occur when third parties are affected by market transactions.",
    "Negative externalities cause social costs not reflected in market prices.",
    "Positive externalities create social benefits not reflected in market prices.",
    "Public goods are non-excludable and non-rival in consumption.",
    "Market failure occurs when markets allocate resources inefficiently.",
    "Government intervention may correct market failures using taxes or subsidies.",

    "GDP measures the total value of final goods and services produced in an economy.",
    "Economic growth is the increase of real output over time.",
    "Inflation is a sustained increase in the general price level.",
    "Deflation is a sustained decrease in the general price level.",
    "Unemployment is the share of the labor force actively seeking work but jobless.",
    "Productivity measures output per unit of labor input.",
    "Monetary policy controls interest rates and money supply to stabilize the economy.",
    "Central banks influence inflation and employment using policy tools.",
    "Fiscal policy uses government spending and taxation to affect demand.",
    "Budget deficits occur when government spending exceeds government revenue.",

    "National debt is the accumulation of government borrowing over time.",
    "Interest rates affect borrowing costs and investment decisions.",
    "Savings provide funds that support investment and capital accumulation.",
    "International trade allows countries to specialize based on comparative advantage.",
    "Comparative advantage exists when a country has lower opportunity cost of production.",
    "Imports are goods and services purchased from other countries.",
    "Exports are goods and services sold to other countries.",
    "Exchange rates influence the relative prices of imports and exports.",
    "Trade barriers include tariffs, quotas, and regulatory restrictions.",
    "Economic expectations influence consumer spending and business investment decisions."
]