DOMAIN_name = "law"

TEXTS = [
    "Law is a system of rules that regulates behavior in society.",
    "Legal systems define rights and obligations for individuals and institutions.",
    "The rule of law requires that laws apply equally to everyone, including authorities.",
    "Legislatures create statutes through formal lawmaking processes.",
    "Courts interpret laws and resolve disputes through legal procedures.",
    "Judges apply legal rules to cases using facts and evidence.",
    "Legal certainty depends on clear and predictable legal interpretation.",
    "Constitutions define foundational principles and limits on government power.",
    "Statutory law refers to written laws enacted by legislative bodies.",
    "Regulations are detailed rules created by authorized administrative agencies.",

    "Criminal law addresses offenses against the state and public order.",
    "Civil law resolves disputes between private parties such as individuals or companies.",
    "Administrative law governs actions and decisions of public agencies.",
    "Due process ensures fairness in legal procedures and government actions.",
    "Presumption of innocence requires proof before punishment is imposed.",
    "Legal standards define thresholds such as beyond reasonable doubt or preponderance.",
    "Evidence supports or challenges legal claims and factual allegations in court.",
    "Burden of proof determines which party must prove their claim.",
    "Legal remedies include damages, injunctions, and specific performance.",
    "Legal sanctions deter unlawful behavior through penalties or restrictions.",

    "Contracts are legally enforceable agreements between parties.",
    "Contract formation requires offer, acceptance, and consideration in many systems.",
    "Breach of contract occurs when a party fails to fulfill contractual obligations.",
    "Tort law addresses civil wrongs that cause harm to others.",
    "Negligence involves failing to meet a reasonable standard of care.",
    "Liability determines legal responsibility for damages or harm.",
    "Property law governs ownership and transfer of land and assets.",
    "Ownership grants rights to use, control, and transfer property.",
    "Consumer protection law prevents unfair practices and protects buyers.",
    "Employment law regulates relationships between employers and workers.",

    "Human rights law protects dignity and fundamental freedoms of people.",
    "Equality before the law requires similar cases to be treated consistently.",
    "Anti-discrimination rules prohibit unfair treatment based on protected characteristics.",
    "International law governs relations and agreements between sovereign states.",
    "Treaties are formal international agreements recognized under international law.",
    "Legal compliance means following laws, regulations, and binding obligations.",
    "Law enforcement agencies uphold laws and maintain public order.",
    "Judicial review assesses whether laws comply with constitutional principles.",
    "Separation of powers divides authority among executive, legislative, and judicial branches.",
    "Checks and balances prevent concentration of power in a single institution.",

    "Legal interpretation clarifies meaning when legal language is ambiguous.",
    "Statutory interpretation considers text, context, and legislative intent.",
    "Legal reasoning applies logic to connect facts, rules, and conclusions.",
    "Precedent means prior court decisions can guide later rulings.",
    "Case law develops when courts interpret statutes and legal principles over time.",
    "Legal reforms update laws to reflect social change and new challenges.",
    "Public law governs relationships between citizens and the state.",
    "Private law governs relationships between individuals and private entities.",
    "Legal institutions maintain stability by resolving disputes peacefully.",
    "Law supports social order by establishing enforceable rules and accountability."
]