DOMAIN_name = "mathematics"

TEXTS = [
    "A function maps each input in its domain to exactly one output in its codomain.",
    "Linear functions have constant rate of change represented by slope.",
    "Quadratic functions form parabolas and can have zero, one, or two real roots.",
    "Polynomials are algebraic expressions formed by sums of terms with integer exponents.",
    "Factoring decomposes polynomials into products of simpler expressions.",
    "The quadratic formula solves ax^2 + bx + c = 0 for x values.",
    "Exponential functions model growth and decay with constant proportional change.",
    "Logarithms are inverse functions of exponentials and simplify multiplicative relationships.",
    "Systems of linear equations can be solved by elimination, substitution, or matrices.",
    "Inequalities describe solution sets that form intervals on the real number line.",

    "Absolute value represents distance from zero and is always nonnegative.",
    "Functions can be represented by graphs, tables, or algebraic expressions.",
    "The inverse of a function swaps input-output pairs when the function is one-to-one.",
    "Domain restrictions may apply due to denominators, square roots, or logarithms.",
    "Sequences are ordered lists defined by explicit or recursive rules.",
    "Arithmetic sequences have constant differences between consecutive terms.",
    "Geometric sequences have constant ratios between consecutive terms.",
    "Series represent sums of sequence terms and can converge or diverge.",
    "Limits describe the value a function approaches near a point.",
    "Continuity means a function has no breaks and limit equals value at a point.",

    "Derivatives represent instantaneous rates of change of a function.",
    "The derivative of a function is defined using the limit of a difference quotient.",
    "The chain rule differentiates composite functions by multiplying derivatives.",
    "The product rule differentiates products of functions using a specific formula.",
    "The quotient rule differentiates ratios of functions using numerator and denominator derivatives.",
    "Critical points occur where derivative is zero or undefined and may indicate extrema.",
    "Optimization problems use derivatives to find maxima and minima under constraints.",
    "Integrals represent accumulation and can compute areas under curves.",
    "Definite integrals evaluate net area between a function and the x-axis over an interval.",
    "The fundamental theorem of calculus links differentiation and integration.",

    "Vectors have magnitude and direction and can be added component-wise.",
    "Dot products measure similarity between vectors and relate to projection.",
    "Cross products produce vectors perpendicular to two input vectors in three dimensions.",
    "Matrices represent linear transformations and systems of equations compactly.",
    "Matrix multiplication is associative but generally not commutative.",
    "Determinants indicate matrix invertibility and scaling of linear transformations.",
    "Eigenvalues and eigenvectors describe directions preserved by linear transformations.",
    "Probability measures likelihood of outcomes in a sample space.",
    "Conditional probability quantifies probability given that another event occurs.",
    "Bayes’ theorem updates probabilities using evidence and prior beliefs.",

    "Random variables assign numbers to outcomes of random processes.",
    "Expected value represents the long-run average outcome of a random variable.",
    "Variance measures spread of values around the mean in a probability distribution.",
    "Normal distributions appear in many natural processes and statistical models.",
    "Hypothesis testing evaluates whether evidence supports a claim about a population.",
    "Confidence intervals estimate population parameters with quantified uncertainty.",
    "Correlation measures strength and direction of association between variables.",
    "Regression models describe relationships between variables and enable predictions.",
    "Mathematical proofs use logical reasoning to establish the truth of statements.",
    "Set theory defines collections of elements and operations like union and intersection."
]