DOMAIN_name = "medicine"

TEXTS = [
    "Medicine studies the prevention, diagnosis, and treatment of disease.",
    "Health is influenced by biological, environmental, and social factors.",
    "Disease occurs when normal physiological function is disrupted.",
    "Diagnosis identifies medical conditions using evidence, symptoms, and tests.",
    "Treatment aims to reduce symptoms and restore normal body function.",
    "Prevention reduces risk through vaccination, lifestyle changes, and screening.",
    "Infectious diseases are caused by pathogens such as bacteria and viruses.",
    "Noninfectious diseases can involve genetics, lifestyle, or environmental exposure.",
    "The immune system defends the body by recognizing harmful antigens.",
    "Inflammation is a protective response to injury or infection.",

    "Innate immunity provides rapid, non-specific defense mechanisms.",
    "Adaptive immunity produces specific responses and long-term immune memory.",
    "Antibodies bind to antigens and help neutralize pathogens.",
    "Vaccination stimulates immune memory to prevent future infection.",
    "Antibiotics treat bacterial infections but are ineffective against viruses.",
    "Antibiotic resistance evolves when bacteria adapt to selective drug pressure.",
    "Viruses replicate inside host cells using cellular machinery.",
    "Epidemiology studies patterns and causes of disease in populations.",
    "Transmission can occur via droplets, contact, aerosols, or contaminated surfaces.",
    "Incubation period is the time between infection and symptom onset.",

    "Anatomy studies the structure of organs and body systems.",
    "Physiology studies how organ systems function and maintain balance.",
    "Homeostasis regulates internal conditions like temperature and blood pH.",
    "The cardiovascular system delivers oxygen and nutrients to tissues.",
    "The respiratory system exchanges oxygen and carbon dioxide in the lungs.",
    "The nervous system coordinates responses through electrical signaling.",
    "The endocrine system regulates processes through hormones in the bloodstream.",
    "The digestive system breaks down food into absorbable nutrients.",
    "The kidneys regulate fluid balance and remove waste from blood.",
    "The musculoskeletal system enables movement and physical support.",

    "Medical imaging includes X-ray, CT, MRI, and ultrasound for diagnosis.",
    "Laboratory tests measure biomarkers to support clinical decisions.",
    "Clinical trials evaluate safety and effectiveness of medical interventions.",
    "Evidence-based medicine uses research findings to guide treatment choices.",
    "Risk-benefit analysis evaluates potential benefits versus harms of treatment.",
    "Side effects are unintended outcomes that may occur from medications.",
    "Dosage and pharmacokinetics affect drug effectiveness and toxicity.",
    "Acute diseases develop rapidly and may require urgent care.",
    "Chronic diseases persist long-term and require ongoing management.",
    "Mental health influences cognition, emotion, and daily functioning.",

    "Stress can affect immune function and cardiovascular health outcomes.",
    "Nutrition supports metabolic function through essential nutrients and energy.",
    "Exercise improves cardiovascular fitness and metabolic regulation.",
    "Public health programs reduce disease burden through prevention strategies.",
    "Screening detects disease risk before symptoms become severe.",
    "Healthcare systems coordinate resources to deliver medical services.",
    "Access to care affects outcomes across socioeconomic groups.",
    "Patient safety reduces preventable harm in healthcare delivery.",
    "Medical ethics guides decisions about autonomy, consent, and harm reduction.",
    "Confidentiality protects sensitive patient health information."
]