DOMAIN_name = "physics"

TEXTS = [
    "Newton's laws describe how forces affect the motion of objects.",
    "A net force causes acceleration proportional to mass through F = ma.",
    "Momentum is conserved in isolated systems during interactions and collisions.",
    "Impulse is the product of force and time and equals change in momentum.",
    "Work is done when a force causes displacement in the direction of the force.",
    "Kinetic energy equals one half mass times velocity squared.",
    "Potential energy can be stored due to position in a gravitational field.",
    "Mechanical energy is conserved when only conservative forces act.",
    "Friction converts mechanical energy into thermal energy in real systems.",
    "Power measures the rate of energy transfer or work done over time.",

    "Circular motion requires centripetal acceleration directed toward the center.",
    "Centripetal force can be provided by tension, gravity, or friction depending on the system.",
    "Projectile motion can be separated into independent horizontal and vertical components.",
    "Vectors represent quantities with both magnitude and direction.",
    "Velocity is the time rate of change of displacement in one dimension or more.",
    "Acceleration is the time rate of change of velocity and can be nonuniform.",
    "Free-body diagrams help analyze forces acting on an object in equilibrium or motion.",
    "Equilibrium occurs when net force equals zero and acceleration is zero.",
    "Drag force depends on speed, area, and fluid density in many cases.",
    "Terminal velocity occurs when drag force balances gravitational force during a fall.",

    "Pressure is defined as force per unit area and depends on applied force distribution.",
    "Fluids exert pressure that increases with depth due to the weight of the fluid above.",
    "Buoyant force equals the weight of displaced fluid according to Archimedes' principle.",
    "Density is mass per volume and influences floating behavior in fluids.",
    "Temperature relates to average kinetic energy of particles in a system.",
    "Heat is energy transfer due to temperature differences between systems.",
    "The first law of thermodynamics relates internal energy, heat, and work.",
    "Entropy is a measure of disorder or number of microstates available to a system.",
    "Thermal conduction transfers energy through particle collisions in a material.",
    "Convection transfers heat through bulk fluid motion driven by density differences.",

    "Waves transfer energy and momentum without net transport of matter over distance.",
    "Wave speed equals frequency multiplied by wavelength for periodic waves.",
    "Standing waves form when two waves interfere in opposite directions.",
    "Sound waves are longitudinal pressure waves that require a medium to propagate.",
    "The Doppler effect changes observed frequency due to relative motion between source and observer.",
    "Light behaves as an electromagnetic wave and can also show particle-like properties.",
    "Reflection follows the law of equal angles between incidence and reflection.",
    "Refraction occurs when wave speed changes across a boundary between media.",
    "Snell's law relates refractive index to incidence and refraction angles.",
    "Lenses form images by refraction and depend on focal length and curvature.",

    "Electric charge is conserved and comes in positive and negative forms.",
    "Coulomb's law describes the force between charges as proportional to product of charges.",
    "Electric fields represent force per unit charge experienced by a test charge.",
    "Voltage is electric potential difference that drives current in circuits.",
    "Current is the flow rate of electric charge through a conductor.",
    "Ohm's law relates voltage, current, and resistance in many materials.",
    "Power in an electric circuit equals voltage times current for steady conditions.",
    "Magnetic fields arise from moving charges and produce forces on currents.",
    "Electromagnetic induction generates voltage from changing magnetic flux over time.",
    "Maxwell's equations unify electricity, magnetism, and electromagnetic wave behavior."
]