DOMAIN_name = "weapons"

TEXTS = [
    "Weapons are tools designed to provide combat capability or cause physical harm.",
    "Weapons have shaped conflict outcomes throughout human history.",
    "Weapons influence military strategy and defense planning decisions.",
    "Societies regulate weapons to reduce misuse and public safety risks.",
    "Weapon policy balances security needs with harm reduction goals.",
    "Arms control limits development, deployment, or transfer of weapon systems.",
    "Disarmament reduces or eliminates weapon stockpiles through agreements.",
    "International treaties may restrict certain categories of weapons.",
    "Weapons proliferation can increase instability and escalation risks.",
    "Deterrence aims to prevent conflict by threatening credible retaliation.",

    "Military capability includes training, logistics, intelligence, and weapon systems.",
    "Weapon technology evolves alongside scientific and industrial development.",
    "Weapon systems are evaluated for reliability, cost, and strategic impact.",
    "Defense planning considers threats, alliances, and resource constraints.",
    "Security studies analyze how weapons affect regional and global stability.",
    "Weapons can raise ethical concerns due to civilian harm and escalation.",
    "International humanitarian law restricts weapon use during armed conflict.",
    "Rules of engagement define conditions under which force may be used.",
    "Civilian protection is a major concern in conflict and security policy.",
    "Arms races occur when states increase weapons to gain advantage over rivals.",

    "Weapons can shift power dynamics and influence international relations.",
    "Military expenditure reflects national priorities for defense and security.",
    "Weapon procurement involves budgeting, testing, and contracting processes.",
    "Strategic stability refers to conditions that reduce incentives for escalation.",
    "Weapons modernization updates platforms to improve effectiveness and survivability.",
    "Defense alliances influence weapon planning through collective deterrence goals.",
    "Weapons oversight requires accountability, audits, and legal constraints.",
    "Weapon ownership laws vary across countries and legal systems.",
    "Licensing requirements restrict access to certain weapon categories.",
    "Weapon restrictions are enforced through regulatory and policing mechanisms.",

    "Weapons appear in historical studies of wars, empires, and geopolitics.",
    "Weapon development reflects changes in tactics and battlefield conditions.",
    "Industrial capacity influences scale and speed of weapon production.",
    "Weapons can affect negotiation outcomes in diplomacy and conflict resolution.",
    "Peace agreements may include provisions limiting weapons or troop deployments.",
    "Weapons increase risks of accidental harm or unintended escalation events.",
    "Security risk assessments include analysis of weapon availability and misuse.",
    "Conflict prevention reduces incentives for armed confrontation through diplomacy.",
    "Weapons policy is shaped by cultural, political, and social factors.",
    "Public debates often address weapon safety, regulation, and enforcement.",

    "Weapons research considers ethical, legal, and strategic consequences of systems.",
    "Defense doctrine describes how forces and weapons may be used in operations.",
    "Military balance compares relative capabilities between rival actors.",
    "Weapons influence perceptions of threat, vulnerability, and deterrence credibility.",
    "Security cooperation may involve transparency measures and arms limitations.",
    "Verification mechanisms support arms control treaty compliance monitoring.",
    "Transparency reduces mistrust and misunderstanding between competing states.",
    "Weapons are studied as part of international security and strategic stability.",
    "Weapon regulation seeks to reduce violence and instability in society.",
    "Weapons are analyzed in political science and international security research."
]